### ISSUE TITLE
若干测试反馈

### ISSUE THREAD

**Issue by KJH-x** [flwfdd/MergeMusicDesktop#1]
![截图_20221216115031](https://user-images.githubusercontent.com/53437291/208017832-2154b25d-77af-4422-9daa-fa498867a146.png)
![截图_20221216115529](https://user-images.githubusercontent.com/53437291/208018429-687fa48d-c034-4fe4-b186-1ab637fed472.png)

1. 如图1在搜索的输入框输入会有白底闪动，其他输入框没有类似状况。
2. 如图2似乎此处功能应该是：”你的（此收藏夹的）新名字是？“
3. 播放列表回退貌似无法前进（？
4. 重启之后下载成功项无了
5. 收藏夹里的删除按钮应该是删除选中歌曲比较符合逻辑，删除收藏夹应该放到收藏夹管理里

不重要的小问题：
- 要是能播放本地歌曲就更好了
- 悬浮提示的延时可以短一点？（我觉得是可以没有延时）
- 正在播放的歌曲，操作栏符号应该为暂停且有暂停功能吧（）
- 搜索返回键没有把输入框的内容还原成上个搜索，有点怪，可能只是我个人习惯（

**Comment by flwfdd** [comment]
非常感谢您提出的建议_(:з」∠) _

1235都修了，4加了句说明文案（逃

悬浮提示、搜索返回也改掉了，正在播放那个实在太细了改起来还有点小麻烦就不管了先2333

下载成功项没有长期显示、本地文件没有支持都是考虑到这些文件可能会很快地被用户删除或移动，而让一些东西变成“死链”，破坏了一种完整性的感觉....？所以暂时没有加，时间也不大够了。

（1那个问题我一直都知道，但一直以为是框架本身的问题，也没意识到“其他输入框没有问题”，真是醍醐灌顶啊！最后其实就删了原来的重新建了一个输入框就解决了，也不知道原来的那个哪里抽风hhhh

**Comment by KJH-x** [comment]
![IMG_5940](https://user-images.githubusercontent.com/53437291/208221562-81115095-b32b-44a4-819c-0762f76c7add.GIF)
